### ISSUE TITLE
在浏览器控制台中动态引入jq库

### ISSUE THREAD

**Issue by feiyuWeb** [feiyuWeb/Blog#25]
// 创建元素，设置地址
var script = document.createElement('script');
script.src = "https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js";
// 添加到head标签中
document.getElementsByTagName('head')[0].appendChild(script);

**Comment by feiyuWeb** [comment]
### 媒体查询 移动端适配
移动端加上
```html
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```
width=device-width ：表示宽度是设备屏幕的宽度
initial-scale=1.0：表示初始的缩放比例
minimum-scale=1.0：表示最小的缩放比例
maximum-scale=1.0：表示最大的缩放比例
user-scalable=no：表示用户是否可以调整缩放比例

使用link时
```html
<link rel="stylesheet" media="(max-width: 800px)" href="example.css" ><link rel="stylesheet" media="(max-width: 800px)" href="example.css" >
```

直接在style中使用
```css
<style>
@media (max-width: 600px) {
  .facet_sidebar {
    display: none;
  }
}
</style>
```
