### ISSUE TITLE
npm及js小技巧

### ISSUE THREAD

**Issue by feiyuWeb** [feiyuWeb/Blog#3]
### 查看npm上各种包的版本等信息

查看所有版本
> npm view <packagename> versions 
查看最近版本的详细信息
> npm view <packagename> 

npm安装最新版本的bao
> npm install <packagename>@latest

npm升级包的版本
> npm update <packagename>
> npm update <packagename>@2.5  // 指定升级到某个版本

npm删除某个包
> npm remove <packagename>

> `npm init` 命令用来初始化一个简单的 `package.json` 文件

依赖包安装
> npm install <packagename>
> 依赖管理是 `npm` 的核心功能，原理就是执行 `npm install` 从 `package.json` 中的 `dependencies, devDependencies` 将依赖包安装到当前目录的 `./node_modules` 文件夹中

`CSS` 的伪元素是个很強大的东西，我们可以利用他做很多运用，通常为了做一些效果，`content:" "` 多半会留空，但其实可以在里面写上 `attr` 抓资料哦

```js
<div data-msg="Open this file in Github Desktop">  
hover
</div>

div{
  width:100px;
  border:1px solid red;  
  position:relative;
}
div:hover:after{
  content:attr(data-msg);
  position:absolute;
  font-size: 12px;
  width:200%;
  line-height:30px;
  text-align:center;
  left:0;
  top:25px;
  border:1px solid green;
}
```

最终效果如图：
![图片](https://i.loli.net/2019/04/06/5ca8625e475dc.png)

### 单行写一个评级组件
> "★★★★★☆☆☆☆☆".slice(5 - rate, 10 - rate);定义一个变量rate是1到5的值

效果如图：
![评论](https://i.loli.net/2019/04/06/5ca863ab0a5f7.png)

### JavaScript 错误处理的方式的正确姿势
```js
try {
    something
} catch (e) {
    window.location.href =
        "http://stackoverflow.com/search?q=[js]+" +
        e.message;
}
```
> 报错会自动跳到stackoverflow.com上去搜素

### 一行代码找到网页上所有的标签并标注不同颜色
```js
[].forEach.call($$("*"),function(a){
    a.style.outline="1px solid #"+(~~(Math.random()*(1<<24))).toString(16)
})
```

### 优雅得取随机字符串
```js
Math.random().toString(16).substring(2)
// "aa2ce73b56d44"
Math.random().toString(36).substring(2) 
// "l6pdgttxk3o"
```

### 多种写法的匿名函数自执行
```js
(function(){})();
~ function() {}();
! function() {}();
+ function() {}();
- function() {}();
```

### js中优雅的取整
```js
let a = ~~2.5 // 2
let b = 2.35 >> 0 // 2
// 相当于parseInt(2.5) -- // 2 
```

### 优雅的实现金钱格式化：1234567890 --> 1,234,567,890
```js
/*正则方式*/
var test1 = '1234567890'
var format = test1.replace(/\B(?=(\d{3})+(?!\d))/g, ',')

console.log(format) // 1,234,567,890

/*非正则方式*/
 function formatCash(str) {
       return str.split('').reverse().reduce((prev, next, index) => {
            return ((index % 3) ? next : (next + ',')) + prev
       })
}
console.log(formatCash('1234567890')) // 1,234,567,890
```

### 实现标准JSON的深拷贝
```js
var a = {
    a: 1,
    b: { c: 1, d: 2 }
}
var obj=JSON.parse(JSON.stringify(a))
```
### 用js的方法下载图片
```js
function downloadImg(url) { 
  fetch(url).then(res =>
    res.blob().then(blob => {
      const a = document.createElement('a')
      const url = window.URL.createObjectURL(blob)
      a.href = url
      a.download = '哈哈'
      a.click()
      window.URL.revokeObjectURL(url)
    })
  )
}
```

### js中sort排序的正序和倒序
```js
/**
* sort() 方法用于对数组的元素进行排序
* arrayObject.sort(sortby)
* sortby 可选。规定排序顺序。必须是函数。
*/

const arr=[3,1,16,34,30];
arr.sort((m,n)=>m-n) // [1, 3, 16, 30, 34]
arr.sort((m,n)=>n-m) // [34, 30, 16, 3, 1]
```

### 用最短的代码实现一个长度为m(6)且值都n(8)的数组
```js
Array(6).fill(8)  // [8,8,8,8,8,8]
```
### 一句代码找出当前页面所有的图片
```js
let arr = []
Array.from(document.images).forEach(item=>{
	arr.push(item.getAttribute('src'))
})
console.log(JSON.stringify(arr))
```

**Comment by feiyuWeb** [comment]
### 获取链接 `https://www.baidu.com?name=jawil&age=23` name的value值
```js
function getParamName(attr) {

  let match = RegExp(`[?&]${attr}=([^&]*)`) //分组运算符是为了把结果存到exec函数返回的结果里
    .exec(window.location.search)
  //["?name=jawil", "jawil", index: 0, input: "?name=jawil&age=23"]
  return match && decodeURIComponent(match[1].replace(/\+/g, ' ')) // url中+号表示空格,要替换掉
}

console.log(getParamName('name'))  // "jawil"
```

**Comment by feiyuWeb** [comment]
### 有趣的文字效果
```js
    <div class="container">
      <h1 class="blog-title" style="">墨兰</h1>
      <h2 class="blog-description" style="">
        <div id="binft">
          比失败更令人心痛<span style="color: rgb(76, 110, 219);">h</span
          ><span style="color: rgb(175, 240, 91);">C</span
          ><span style="color: rgb(26, 199, 194);">]</span
          ><span style="color: rgb(35, 171, 216);">/</span
          ><span style="color: rgb(110, 64, 170);">6</span>
        </div>
        <script>
          var binft = function(r) {
            function t() {
              return b[Math.floor(Math.random() * b.length)];
            }
            function e() {
              return String.fromCharCode(94 * Math.random() + 33);
            }
            function n(r) {
              for (
                var n = document.createDocumentFragment(), i = 0;
                r > i;
                i++
              ) {
                var l = document.createElement('span');
                (l.textContent = e()), (l.style.color = t()), n.appendChild(l);
              }
              return n;
            }
            function i() {
              var t = o[c.skillI];
              c.step
                ? c.step--
                : ((c.step = g),
                  c.prefixP < l.length
                    ? (c.prefixP >= 0 && (c.text += l[c.prefixP]), c.prefixP++)
                    : 'forward' === c.direction
                    ? c.skillP < t.length
                      ? ((c.text += t[c.skillP]), c.skillP++)
                      : c.delay
                      ? c.delay--
                      : ((c.direction = 'backward'), (c.delay = a))
                    : c.skillP > 0
                    ? ((c.text = c.text.slice(0, -1)), c.skillP--)
                    : ((c.skillI = (c.skillI + 1) % o.length),
                      (c.direction = 'forward'))),
                (r.textContent = c.text),
                r.appendChild(
                  n(
                    c.prefixP < l.length
                      ? Math.min(s, s + c.prefixP)
                      : Math.min(s, t.length - c.skillP)
                  )
                ),
                setTimeout(i, d);
            }
            var l = '',
              o = ['努力成为你想成为的人'].map(function(r) {
                return r + '';
              }),
              a = 2,
              g = 1,
              s = 5,
              d = 75,
              b = [
                'rgb(110,64,170)',
                'rgb(150,61,179)',
                'rgb(191,60,175)',
                'rgb(228,65,157)',
                'rgb(254,75,131)',
                'rgb(255,94,99)',
                'rgb(255,120,71)',
                'rgb(251,150,51)',
                'rgb(226,183,47)',
                'rgb(198,214,60)',
                'rgb(175,240,91)',
                'rgb(127,246,88)',
                'rgb(82,246,103)',
                'rgb(48,239,130)',
                'rgb(29,223,163)',
                'rgb(26,199,194)',
                'rgb(35,171,216)',
                'rgb(54,140,225)',
                'rgb(76,110,219)',
                'rgb(96,84,200)'
              ],
              c = {
                text: '',
                prefixP: -s,
                skillI: 0,
                skillP: 0,
                direction: 'forward',
                delay: a,
                step: g
              };
            i();
          };
          binft(document.getElementById('binft'));
        </script>
      </h2>
    </div>
```

**Comment by feiyuWeb** [comment]
### 如何修改chrome记住密码后自动填充表单的黄色背景 
```css
input:-webkit-autofill, textarea:-webkit-autofill, select:-webkit-autofill {
    background-color: rgb(250, 255, 189); /* #FAFFBD; */
    background-image: none;
    color: rgb(0, 0, 0);
  }


```

**Comment by feiyuWeb** [comment]
### 让页面里的字体变清晰，变细用CSS怎么做？
```css
-webkit-font-smoothing: antialiased;
```

**Comment by feiyuWeb** [comment]
### 让ios上滑动更加流畅
```css
-webkit-overflow-scrolling: touch;
```

**Comment by feiyuWeb** [comment]
如何将浮点数点左边的数每三位添加一个逗号
```js
function commafy(num){
    return num && num
        .toString()
        .replace(/(\d)(?=(\d{3})+\.)/g, function($1, $2){
            return $2 + ',';
        });
  }
```

**Comment by feiyuWeb** [comment]
### 开启硬件加速
```css
//目前，像Chrome/Filefox/Safari/IE9+以及最新版本Opera都支持硬件加速，当检测到某个DOM元素应用了某些CSS规则时就会自动开启，从而解决页面闪白，保证动画流畅。
.css {
    -webkit-transform: translate3d(0,0,0);
    -moz-transform: translate3d(0,0,0);
    -ms-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
}

```

**Comment by feiyuWeb** [comment]
### 手机上的多行省略
```css
.overflow-hidden{
    display: box !important;
    display: -webkit-box !important;
    overflow: hidden;
    text-overflow: ellipsis;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 4;/*第几行出现省略号*/
    /*text-align:justify;不能和溢出隐藏的代码一起写，会有bug*/
}

```

**Comment by feiyuWeb** [comment]
### 长时间按住页面闪退
```css
.element {
    -webkit-touch-callout: none;
}
```

**Comment by feiyuWeb** [comment]
### 改变输入框内提示文字颜色
```css
::-webkit-input-placeholder { /* WebKit browsers */
    color: #999; }
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */
    color: #999; }
::-moz-placeholder { /* Mozilla Firefox 19+ */
    color: #999; }
:-ms-input-placeholder { /* Internet Explorer 10+ */
    color: #999; }
input:focus::-webkit-input-placeholder{ color:#999; }

```

**Comment by feiyuWeb** [comment]
### 自动播放音乐
```js
//JS绑定自动播放（操作window时，播放音乐）
$(window).one('touchstart', function(){
    music.play();
})

//微信下兼容处理
document.addEventListener("WeixinJSBridgeReady", function () {
    music.play();
}, false);

```

**Comment by feiyuWeb** [comment]
### 消除transtration闪屏

```css
.css {
    -webkit-transform-style: preserve-3d;
    -webkit-backface-visibility: hidden;
    -webkit-perspective: 1000;
}
```
