### ISSUE TITLE
js

### ISSUE THREAD

**Issue by feiyuWeb** [feiyuWeb/Blog#38]

**Comment by feiyuWeb** [comment]
```js
/**
 *  所以函数返回值是数字的相加
 */

var obj = {
	a: function () {
		return "1a"
	},
	b: function () {
		return 6
	},
	c: function () {
		return "5"
	},
	d: function () {
		return "asd"
	},
}

/**
 * 第一种方法
 */

Object.keys(obj)
	.map((o) => obj[o]())
	.filter((v) => !isNaN(v))
	.reduce((pre, next) => Number(pre) + Number(next))

/**
 * 第二种方法
 */

let arr = []
Object.keys(obj).forEach((element) => {
	if (!isNaN(obj[element]())) {
		arr.push(Number(obj[element]()))
	}
})

arr.reduce((pre, next) => pre + next)
```

**Comment by feiyuWeb** [comment]
### 样式
```css
body {
  -webkit-font-smoothing: antialiased; // 平滑像素级别的字体
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  -khtml-user-select: none;
  user-select: none; // 让用户不可选中
}
```
