### ISSUE TITLE
 使用媒体查询@media实现网页跟随系统设置的深色模式改变背景色

### ISSUE THREAD

**Issue by better2021** [feiyuWeb/Blog#50]
手机或电脑选择深色模式时媒体查询中的样式body就会生效

```css
@media screen and (prefers-color-scheme:dark){
  body{
    background-color:#202124;
    color:#eeeeee
  }
}
```
